id = "weapon"
name = "Weapon"
description = "The open source coding agent."
version = "1.1.63"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/weapon"

[agent_servers.weapon]
name = "Weapon"
icon = "./icons/weapon.svg"

[agent_servers.weapon.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/weapon/releases/download/v1.1.63/weapon-darwin-arm64.zip"
cmd = "./weapon"
args = ["acp"]

[agent_servers.weapon.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/weapon/releases/download/v1.1.63/weapon-darwin-x64.zip"
cmd = "./weapon"
args = ["acp"]

[agent_servers.weapon.targets.linux-aarch64]
archive = "https://github.com/anomalyco/weapon/releases/download/v1.1.63/weapon-linux-arm64.tar.gz"
cmd = "./weapon"
args = ["acp"]

[agent_servers.weapon.targets.linux-x86_64]
archive = "https://github.com/anomalyco/weapon/releases/download/v1.1.63/weapon-linux-x64.tar.gz"
cmd = "./weapon"
args = ["acp"]

[agent_servers.weapon.targets.windows-x86_64]
archive = "https://github.com/anomalyco/weapon/releases/download/v1.1.63/weapon-windows-x64.zip"
cmd = "./weapon.exe"
args = ["acp"]
