name: weapon

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  weapon:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /weapon') ||
      startsWith(github.event.comment.body, '/weapon')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run weapon
        uses: anomalyco/weapon/github@latest
        env:
          WEAPON_API_KEY: ${{ secrets.WEAPON_API_KEY }}
          WEAPON_PERMISSION: '{"bash": "deny"}'
        with:
          model: weapon/claude-opus-4-5
